#!/usr/bin/env node

import { program } from "commander";
import * as fs from "fs";
import * as path from "path";
import * as url from "url";
import * as ts from "typescript";
import { generateZod } from "./generator.js";

// @ts-ignore
const __dirname = url.fileURLToPath(new URL('.', import.meta.url));

program
    .name("candid-to-zod")
    .description("Generate Zod schemas from Dfinity Candid (.did.js) files")
    .version("1.0.0")
    .requiredOption("-i, --input <path>", "Path to the input .did.js file (generated by dfx)")
    .requiredOption("-o, --output <path>", "Path to output the generated .ts format")
    .option("--no-infer", "Skip generating TypeScript z.infer<> types", false)
    .action(async (options: any) => {
        try {
            const inputPath = path.resolve(process.cwd(), options.input);
            const outputPath = path.resolve(process.cwd(), options.output);

            if (!fs.existsSync(inputPath)) {
                console.error(`Error: File not found at ${inputPath}`);
                process.exit(1);
            }

            console.log(`Loading IDL from ${inputPath}...`);

            let module: any;
            let tempJsPath: string | null = null;

            if (inputPath.toLowerCase().endsWith('.ts')) {
                const tsContent = fs.readFileSync(inputPath, 'utf8');
                const jsContent = ts.transpileModule(tsContent, {
                    compilerOptions: {
                        module: ts.ModuleKind.ESNext,
                        target: ts.ScriptTarget.ES2020
                    }
                }).outputText;

                tempJsPath = inputPath.replace(/\.ts$/, '.tmp.js');
                fs.writeFileSync(tempJsPath, jsContent);

                const inputUrl = url.pathToFileURL(tempJsPath).href;
                module = await import(inputUrl);
            } else {
                const inputUrl = url.pathToFileURL(inputPath).href;
                module = await import(inputUrl);
            }

            let factoryFn = module.idlFactory;
            if (!factoryFn) {
                // Check for dynamic export names like socio_mainIdlFactory
                for (const key in module) {
                    if (key.endsWith('IdlFactory') && typeof module[key] === 'function') {
                        factoryFn = module[key];
                        break;
                    }
                }
            }

            if (tempJsPath && fs.existsSync(tempJsPath)) {
                fs.unlinkSync(tempJsPath);
            }

            if (!factoryFn) {
                console.error(`Error: Could not find 'idlFactory' or '*IdlFactory' export in ${inputPath}. Did you pass a valid Dfinity interface file?`);
                process.exit(1);
            }

            console.log(`Parsing AST schemas...`);
            const schemaString = generateZod(factoryFn, { inferTypes: !options.infer });

            fs.mkdirSync(path.dirname(outputPath), { recursive: true });
            fs.writeFileSync(outputPath, schemaString, "utf-8");

            console.log(`\n✅ Generated Zod schemas successfully at ${outputPath}`);
        } catch (e: any) {
            console.error("An error occurred during generation:");
            console.error(e.message || e);
            process.exit(1);
        }
    });

program.parse();
